//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dFrontierAppWizard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mui {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mui() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dFrontierAppWizard.Resources.Mui", typeof(Mui).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string Account_Information {
            get {
                return ResourceManager.GetString("Account_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a promotion.
        /// </summary>
        public static string add_a_promotion {
            get {
                return ResourceManager.GetString("add_a_promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hot Deal.
        /// </summary>
        public static string AddHotDeal {
            get {
                return ResourceManager.GetString("AddHotDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Settings.
        /// </summary>
        public static string AdminSettings {
            get {
                return ResourceManager.GetString("AdminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement.
        /// </summary>
        public static string Advertisement {
            get {
                return ResourceManager.GetString("Advertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements.
        /// </summary>
        public static string Advertisements {
            get {
                return ResourceManager.GetString("Advertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string Analytics {
            get {
                return ResourceManager.GetString("Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Login.
        /// </summary>
        public static string ApiLogin {
            get {
                return ResourceManager.GetString("ApiLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Icon.
        /// </summary>
        public static string ApplicationIcon {
            get {
                return ResourceManager.GetString("ApplicationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string BackGroundColor {
            get {
                return ResourceManager.GetString("BackGroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Contact Email.
        /// </summary>
        public static string BillingContactEmail {
            get {
                return ResourceManager.GetString("BillingContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Contact Number.
        /// </summary>
        public static string BillingContactNumber {
            get {
                return ResourceManager.GetString("BillingContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Information.
        /// </summary>
        public static string BillingInformation {
            get {
                return ResourceManager.GetString("BillingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing information creation is unsuccessfully saved. Please correct the error and try again..
        /// </summary>
        public static string BillingInformationFailed {
            get {
                return ResourceManager.GetString("BillingInformationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Zip Code.
        /// </summary>
        public static string BillingZipCode {
            get {
                return ResourceManager.GetString("BillingZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Loyalty Image.
        /// </summary>
        public static string CaptureLoyaltyImage {
            get {
                return ResourceManager.GetString("CaptureLoyaltyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Code.
        /// </summary>
        public static string CardCode {
            get {
                return ResourceManager.GetString("CardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change picture.
        /// </summary>
        public static string change_picture {
            get {
                return ResourceManager.GetString("change_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image or Video.
        /// </summary>
        public static string changeMediaOrVideo {
            get {
                return ResourceManager.GetString("changeMediaOrVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure you want to delete this item ?.
        /// </summary>
        public static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer.
        /// </summary>
        public static string Consumer {
            get {
                return ResourceManager.GetString("Consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumers.
        /// </summary>
        public static string Consumers {
            get {
                return ResourceManager.GetString("Consumers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount(%).
        /// </summary>
        public static string DiscountPercentage {
            get {
                return ResourceManager.GetString("DiscountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Name.
        /// </summary>
        public static string DocName {
            get {
                return ResourceManager.GetString("DocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (minutes).
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiryMonth.
        /// </summary>
        public static string ExpiryMonth {
            get {
                return ResourceManager.GetString("ExpiryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Year.
        /// </summary>
        public static string ExpiryYear {
            get {
                return ResourceManager.GetString("ExpiryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedbacks.
        /// </summary>
        public static string FeedBacks {
            get {
                return ResourceManager.GetString("FeedBacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Deals.
        /// </summary>
        public static string HotDeals {
            get {
                return ResourceManager.GetString("HotDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour(s).
        /// </summary>
        public static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read the Terms and Conditions.
        /// </summary>
        public static string IHaveReadTheTermsAndConditions {
            get {
                return ResourceManager.GetString("IHaveReadTheTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image or Video to Upload.
        /// </summary>
        public static string ImageOrVideo {
            get {
                return ResourceManager.GetString("ImageOrVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industries.
        /// </summary>
        public static string Industries {
            get {
                return ResourceManager.GetString("Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is cooking.
        /// </summary>
        public static string is_cooking {
            get {
                return ResourceManager.GetString("is_cooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Now.
        /// </summary>
        public static string JoinNow {
            get {
                return ResourceManager.GetString("JoinNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link1.
        /// </summary>
        public static string Link1 {
            get {
                return ResourceManager.GetString("Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link2.
        /// </summary>
        public static string Link2 {
            get {
                return ResourceManager.GetString("Link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link3.
        /// </summary>
        public static string Link3 {
            get {
                return ResourceManager.GetString("Link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty Terms And Conditions.
        /// </summary>
        public static string LoyaltyTermsAndConditions {
            get {
                return ResourceManager.GetString("LoyaltyTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Screen.
        /// </summary>
        public static string MainScreen {
            get {
                return ResourceManager.GetString("MainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Title Color.
        /// </summary>
        public static string MainTitleColor {
            get {
                return ResourceManager.GetString("MainTitleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Title Font.
        /// </summary>
        public static string MainTitleFont {
            get {
                return ResourceManager.GetString("MainTitleFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Title Font Size.
        /// </summary>
        public static string MainTitleFontSize {
            get {
                return ResourceManager.GetString("MainTitleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Documents.
        /// </summary>
        public static string MediaDocuments {
            get {
                return ResourceManager.GetString("MediaDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type.
        /// </summary>
        public static string MediaType {
            get {
                return ResourceManager.GetString("MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile App.
        /// </summary>
        public static string MobileApp {
            get {
                return ResourceManager.GetString("MobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name On Card.
        /// </summary>
        public static string NameOnCard {
            get {
                return ResourceManager.GetString("NameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Leads.
        /// </summary>
        public static string NewLeads {
            get {
                return ResourceManager.GetString("NewLeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not selected.
        /// </summary>
        public static string not_selected {
            get {
                return ResourceManager.GetString("not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Frequencies.
        /// </summary>
        public static string NotificationFrequencies {
            get {
                return ResourceManager.GetString("NotificationFrequencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Grouping.
        /// </summary>
        public static string NotificationGrouping {
            get {
                return ResourceManager.GetString("NotificationGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Price.
        /// </summary>
        public static string OriginalPrice {
            get {
                return ResourceManager.GetString("OriginalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment GateWay.
        /// </summary>
        public static string PaymentGateWay {
            get {
                return ResourceManager.GetString("PaymentGateWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Categories.
        /// </summary>
        public static string ProductCategories {
            get {
                return ResourceManager.GetString("ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        public static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotions.
        /// </summary>
        public static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the field {0} must be between {1} and {2}.
        /// </summary>
        public static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferredBy.
        /// </summary>
        public static string ReferredBy {
            get {
                return ResourceManager.GetString("ReferredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is unsuccessfully save. Please correct the error and try again..
        /// </summary>
        public static string Registration_Failed {
            get {
                return ResourceManager.GetString("Registration_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field {0} is required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer.
        /// </summary>
        public static string Retailer {
            get {
                return ResourceManager.GetString("Retailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailers.
        /// </summary>
        public static string Retailers {
            get {
                return ResourceManager.GetString("Retailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Publish.
        /// </summary>
        public static string SaveAndPublish {
            get {
                return ResourceManager.GetString("SaveAndPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for a promotion.
        /// </summary>
        public static string search_for_a_promotion {
            get {
                return ResourceManager.GetString("search_for_a_promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Hot Deals.
        /// </summary>
        public static string SearchForHotDeals {
            get {
                return ResourceManager.GetString("SearchForHotDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        public static string SecurityCode {
            get {
                return ResourceManager.GetString("SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select thumbnail.
        /// </summary>
        public static string select_thumbnail {
            get {
                return ResourceManager.GetString("select_thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Time Frame.
        /// </summary>
        public static string SetTimeFrame {
            get {
                return ResourceManager.GetString("SetTimeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate.
        /// </summary>
        public static string Simulate {
            get {
                return ResourceManager.GetString("Simulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator.
        /// </summary>
        public static string Simulator {
            get {
                return ResourceManager.GetString("Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may not be longer than {1} characters.
        /// </summary>
        public static string strlen {
            get {
                return ResourceManager.GetString("strlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuff.
        /// </summary>
        public static string Stuff {
            get {
                return ResourceManager.GetString("Stuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bFont Size.
        /// </summary>
        public static string TabFontSize {
            get {
                return ResourceManager.GetString("TabFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Key.
        /// </summary>
        public static string TransactionKey {
            get {
                return ResourceManager.GetString("TransactionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Radius(Km).
        /// </summary>
        public static string TriggerRadius {
            get {
                return ResourceManager.GetString("TriggerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload file.
        /// </summary>
        public static string upload_file {
            get {
                return ResourceManager.GetString("upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Message.
        /// </summary>
        public static string VoucherMessage {
            get {
                return ResourceManager.GetString("VoucherMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSiteReference.
        /// </summary>
        public static string WebSiteReference {
            get {
                return ResourceManager.GetString("WebSiteReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
