//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Promotions = new HashSet<Promotion>();
        }
    
        public int Id { get; set; }
        public string BranchName { get; set; }
        public string Location { get; set; }
        public Nullable<int> CountryId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
