//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Products = new HashSet<Product>();
            this.ReatailerIndustries = new HashSet<ReatailerIndustry>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int UserTypeId { get; set; }
        public string Location { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<ReatailerIndustry> ReatailerIndustries { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual UserType UserType1 { get; set; }
    }
}
